[package]
name = "script_service"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
serde = {"version" = "1.0.219", "features" = ["derive"]}
serde_json = "1.0.140"
zmq = "0.10.0"
