{
 "title": "Killua statistics",
 "description": "This is a dashboard for the Discord bot Killua to monitor various statistics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(discord_connected, job)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(discord_api_requests_total, endpoint)"
    }
   },
   {
    "name": "group",
    "label": "Command group",
    "query": {
     "query": "label_values(discord_command_usage, group)"
    }
   },
   {
    "name": "command",
    "label": "Command name",
    "query": {
     "query": "label_values(discord_command_usage{group=~\"$group\"}, command)"
    }
   },
   {
    "name": "command_id",
    "label": "Command ID",
    "query": {
     "query": "label_values(discord_command_usage{group=~\"$group\", command=~\"$command\"}, command_id)"
    }
   },
   {
    "name": "apiKey",
    "query": {
     "query": "label_values(discord_api_key,key)"
    }
   },
   {
    "name": "apiUrl",
    "query": {
     "query": "label_values(discord_api_url,url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Installs Over Time",
   "type": "timeseries",
   "description": "Number of users that have installed Killua over time",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "discord_user_installs{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System health",
   "type": "state-timeline",
   "description": "Showing if all the shards are logged in",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "discord_connected{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "discord_connected{job=~\"$job\",shard=~'[0-9]+'}",
     "legendFormat": "{{job}} | shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Guilds Over Time",
   "type": "timeseries",
   "description": "Number of guilds Killua has been added to over time",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "discord_stat_total_guilds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "description": "How much RAM the bot is using",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_ram_usage{job=~\"$job\"}",
     "legendFormat": "{{job}} : {{shard}}"
    }
   ]
  },
  {
   "title": "Discord Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discord_latency{job=~\"$job\", shard=~\"[0-9]+\"}",
     "legendFormat": "{{job}} : {{shard}}"
    },
    {
     "expr": "discord_latency{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_cpu_usage{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Info logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{service_name=\"python_bot\"} | detected_level = \"info\""
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "description": "How long it takes to scrape the data from prometheus",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Registered users",
   "type": "stat",
   "description": "The amount of users saved in the mongodb database",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_stat_total_registered_users{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Command usage",
   "type": "piechart",
   "description": "Distribution of how often commands were used",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "discord_command_usage", "legendFormat": "{{group}} {{command}}" }
   ]
  },
  {
   "title": "User location",
   "type": "geomap",
   "description": "The estimates country a user is from based on the language they set their Discord to",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "discord_locale{job=\"$job\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "How commands are used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_event_on_interaction_total{job=\"$job\", is_user_installed=\"True\"})",
     "legendFormat": "User installed"
    },
    {
     "expr": "sum(discord_event_on_interaction_total{job=\"$job\", is_user_installed=\"False\"})",
     "legendFormat": "Slash commands"
    },
    {
     "expr": "sum(discord_event_on_command_total{job=\"$job\"})",
     "legendFormat": "Message command"
    }
   ]
  },
  {
   "title": "Commands ran",
   "type": "timeseries",
   "description": "The commands (of any kind) ran in the last 24hrs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "round(delta(discord_event_on_interaction_total{job=\"$job\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(delta(discord_event_on_command_total{job=\"$job\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily active users",
   "type": "timeseries",
   "description": "The amount of users that use Killua daily, reset every 24 hours",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "discord_daily_active_users", "legendFormat": "Daily active users" }
   ]
  },
  {
   "title": "Votes for the bot",
   "type": "timeseries",
   "description": "The upvotes for Killua on sites like top.gg",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "round(delta(discord_votes_total{job=\"$job\"}[1h]))",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Premium users",
   "type": "timeseries",
   "description": "Users who boost the support server or have an active Patreon or Discord bot subscription",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 37 },
   "targets": [
    { "expr": "discord_premium_users", "legendFormat": "Premium users" }
   ]
  },
  {
   "title": "Approximate total users",
   "type": "timeseries",
   "description": "The combined amount of members of all servers Killua is in",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 37 },
   "targets": [
    { "expr": "discord_approximate_user_count", "legendFormat": "Approximate total users" }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "IPC connection time",
   "type": "timeseries",
   "description": "The time the API takes to connect to the zeromq connection for the bot",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "discord_ipc_response_time{job=~\"$job\"}",
     "legendFormat": "Time for successful IPC connection"
    }
   ]
  },
  {
   "title": "Spam requests",
   "type": "timeseries",
   "description": "The amount of requests that are identified as potential hacking attempts",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(delta(discord_api_spam_requests_total{job=~\"$job\"}[10m]))",
     "legendFormat": "Spam requests"
    }
   ]
  },
  {
   "title": "API response time",
   "type": "timeseries",
   "description": "How long Killua API takes to respond",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "discord_api_response_time{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Logs",
   "type": "stat",
   "description": "The type of logs outputted to the console on the bot process",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logging_total{level=\"WARN\"}) OR on() vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(logging_total{level=\"ERROR\"}) OR on() vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(logging_total{level=\"CRITICAL\"}) OR on() vector(0)",
     "legendFormat": "Critical Errors"
    }
   ]
  },
  {
   "title": "Bot critical logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{service_name=\"python_bot\"} | detected_level != \"info\""
    }
   ]
  },
  {
   "title": "API logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{service_name=\"rust_api\"}"
    }
   ]
  },
  {
   "title": "Proxy logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{service_name=\"zmq_proxy\"}"
    }
   ]
  },
  { "title": "API endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Requests for $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "repeat": "endpoint",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(delta(discord_api_requests_total{endpoint=\"$endpoint\", type=\"requests\"}[10m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "round(delta(discord_api_requests_total{endpoint=\"$endpoint\", type=\"success\"}[10m]))",
     "legendFormat": "Successful responses"
    }
   ]
  },
  { "title": "Commands usage by group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Command usage for group $group",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 104 },
   "repeat": "group",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_command_usage{group=~\"$group\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "DB stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Cards in circulation",
   "type": "timeseries",
   "description": "The total number of cards in circulation ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "discord_cards{job=\"$job\"}",
     "legendFormat": "Total cards"
    }
   ]
  },
  {
   "title": "Biggest collection",
   "type": "stat",
   "description": "The largest amount of non fake, restricted slot cards someone has",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_biggest_collection{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total tags registered",
   "type": "timeseries",
   "description": "The number of tags registered overall using Killua",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 167 },
   "targets": [
    { "expr": "discord_tags", "legendFormat": "Tags" }
   ]
  },
  {
   "title": "Total tags registered",
   "type": "timeseries",
   "description": "The number of tags registered overall using Killua",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 167 },
   "targets": [
    { "expr": "discord_tags", "legendFormat": "Tags" }
   ]
  },
  {
   "title": "Todo tasks",
   "type": "timeseries",
   "description": "The number of todo tasks created overall using Killua",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 167 },
   "targets": [
    { "expr": "discord_todos", "legendFormat": "Todo tasks" }
   ]
  }
 ]
}