"""Test harness helpers (paginator, spell use, poll/wyr, DM views, assertions)."""

from .assertions import (
    assert_content_contains,
    assert_content_equals,
    assert_embed_title,
    assert_inventory,
    embed_at,
    last_content,
    reload_user,
)
from .context import respond_to_view
from .dm_view import patch_user_confirm_dm
from .interaction import MockComponentInteraction
from .member_dm import patch_member_rps_select, patch_member_trivia_select
from .paginator import embed_footer_page, press_paginator_button
from .poll_wyr import (
    ListenerFakeButton,
    ListenerFakeRow,
    build_poll_message,
    build_wyr_message,
    cast_vote,
    encrypted_tail_on_button,
    option_button_custom_id,
)
from .spell_use import (
    ATTACK_TIMEOUT_FRAGMENT,
    DEFAULT_ATTACK_SPELL,
    DEFENSE_SUCCESS_FRAGMENT,
    MET_ERROR_FRAGMENT,
    STEAL_TARGET_CARD,
    assert_met_error,
    assert_steal_blocked_by_defense,
    assert_steal_succeeded,
    embed0,
    ensure_no_defense,
    invoke_use,
    make_target_member,
    patch_random_choice,
    respond_defense_with_spell,
    run_attack_against_defender,
    seed_channel_history,
    setup_author_spell,
    setup_met_view_spell,
    setup_target_user,
    target_member,
    use_view_spell_paginator,
)
from .views import find_button, find_select, iter_view_items

__all__ = [
    "ATTACK_TIMEOUT_FRAGMENT",
    "DEFAULT_ATTACK_SPELL",
    "DEFENSE_SUCCESS_FRAGMENT",
    "ListenerFakeButton",
    "ListenerFakeRow",
    "MET_ERROR_FRAGMENT",
    "MockComponentInteraction",
    "STEAL_TARGET_CARD",
    "assert_content_contains",
    "assert_content_equals",
    "assert_embed_title",
    "assert_inventory",
    "assert_met_error",
    "assert_steal_blocked_by_defense",
    "assert_steal_succeeded",
    "build_poll_message",
    "build_wyr_message",
    "cast_vote",
    "embed0",
    "embed_at",
    "embed_footer_page",
    "encrypted_tail_on_button",
    "ensure_no_defense",
    "find_button",
    "find_select",
    "invoke_use",
    "iter_view_items",
    "last_content",
    "make_target_member",
    "option_button_custom_id",
    "patch_member_rps_select",
    "patch_member_trivia_select",
    "patch_random_choice",
    "patch_user_confirm_dm",
    "press_paginator_button",
    "reload_user",
    "respond_defense_with_spell",
    "respond_to_view",
    "run_attack_against_defender",
    "seed_channel_history",
    "setup_author_spell",
    "setup_met_view_spell",
    "setup_target_user",
    "target_member",
    "use_view_spell_paginator",
]
