name: Run API Tests

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'

  # run only if some file in 'api' folder was changed
  test:
    needs: setup
    if: ${{ needs.setup.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Setup
      run: cd api; mv RocketTemplate.toml Rocket.toml;
    - name: Run tests
      run: cargo test -- --test-threads=1
    - name: Run clippy
      run: cargo clippy --all --all-features --tests -- -D warnings
    - name: Run cargo fmt
      run: cargo fmt --all -- --check