name: Run API Tests

on:
  push:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          rust:
            - 'api/**'
  rust:
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup
        run: cd api; mv RocketTemplate.toml Rocket.toml;
      - name: Run tests
        run: cargo test -- --test-threads=1
      - name: Run clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
      - name: Run cargo fmt
        run: cargo fmt --all -- --check