name: Run API Tests

on:
  push:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'  # Run tests only on changes directly in the api folder

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        run: cd api; mv RocketTemplate.toml Rocket.toml; cargo test -- --test-threads=1