name: Run API Tests

on:
  push:
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'

        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.api == 'true'
        steps:
          - name: Setup
            run: cd api; mv RocketTemplate.toml Rocket.toml;
          - name: Run tests
            run: cargo test -- --test-threads=1
          - name: Run clippy
            run: cargo clippy --all --all-features --tests -- -D warnings
          - name: Run cargo fmt
            run: cargo fmt --all -- --check