name: Run API Tests

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'

  # run only if some file in 'api' folder was changed
  test:
    needs: setup
    if: ${{ needs.setup.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mongodb-tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.6.1.deb
          sudo apt install ./mongodb-database-tools-*-100.6.1.deb
          mongorestore --version
          ./dbsetup.sh
      # - name: Initialise MongoDB Database and Collection
      #   run: |
      #     mongo --host localhost:27017 << EOF
      #     use Killua;
      #     db.createCollection("api-stats");
      #     EOF
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup config.json
        run: |
          echo '{"mongodb": "mongodb://localhost:27017/Killua"}' > config.json
      - name: Setup Rocket.toml
        run: mv api/RocketTemplate.toml api/Rocket.toml
      - name: Run tests
        run: cargo test -- --test-threads=1
        working-directory: api
      - name: Run clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
        working-directory: api
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: api
